---
name: Cron actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - uses: "actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac" # v4

        - name: HACS validation
          uses: "hacs/action@main"
          with:
            category: "integration"
            ignore: brands

        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"
